FROM node:20.7.0-bullseye-slim as build

WORKDIR /app

COPY . .

RUN npm install
RUN npx tsc

FROM node:20.7.0-bullseye-slim

WORKDIR /app

COPY --from=build /app/package*.json ./
COPY --chown=node:node --from=build /app/build ./build

RUN npm install --omit=dev

USER node

ENTRYPOINT node ./build/server.js